# Generated by Django 4.1.7 on 2023-04-07 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TSysUser',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('introduce', models.TextField(blank=True, null=True)),
                ('usertype', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 't_sys_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TWxUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=50)),
                ('class_id', models.IntegerField(blank=True, null=True)),
                ('u_name', models.CharField(blank=True, max_length=20, null=True)),
                ('face_encoding', models.TextField(blank=True, null=True)),
                ('kao_qin', models.IntegerField(blank=True, null=True)),
                ('picture_url', models.CharField(blank=True, max_length=255, null=True)),
                ('student_num', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 't_wx_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('words', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('creator', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'user_info_task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField()),
                ('u_name', models.CharField(max_length=20)),
                ('kq_time', models.DateTimeField(blank=True, null=True)),
                ('student_num', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 't_class',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TStudent',
            fields=[
                ('stu_id', models.AutoField(primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=15)),
                ('class_name', models.CharField(max_length=15)),
                ('college_name', models.CharField(max_length=15)),
                ('face_url', models.CharField(max_length=100)),
                ('openid', models.CharField(blank=True, db_column='openID', max_length=30, null=True)),
            ],
            options={
                'db_table': 't_student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TTea',
            fields=[
                ('tea_id', models.AutoField(primary_key=True, serialize=False)),
                ('tea_name', models.CharField(max_length=15)),
                ('tea_openid', models.CharField(db_column='tea_openID', max_length=30)),
            ],
            options={
                'db_table': 't_tea',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TCourse',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=15)),
                ('tea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='WX_api.ttea')),
            ],
            options={
                'db_table': 't_course',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Chooseinfo',
            fields=[
                ('opt_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('kqstate', models.CharField(blank=True, db_column='kqState', max_length=11, null=True)),
                ('class_field', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.DO_NOTHING, to='WX_api.tcourse')),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WX_api.tstudent')),
            ],
            options={
                'db_table': 'chooseInfo',
                'managed': True,
            },
        ),
    ]
